#!/bin/bash

#Скрипт закачки недостающих версий платформы 1С 
#Работает после скрипта lb-1c-srav-platform-

#read -p "Пользователь:" USERNAME
#read -p "Пароль:" PASSWORD
USERNAME=$1
PASSWORD=$2

UPLOADDIRPLATFORM=/tmp/dist1c
#Функция для сравнения версий
function version_platform { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

#Сравнение версий, если версия ниже 8.3.12.1469 то качаем после else
#if [ $(version_platform $VERPLATFORM) -ge $(version_platform "8.3.14.1469") ]; then


#Подключаемся к серверу 1С
SRC=$(curl -c /tmp/cookies.txt -s -L https://releases.1c.ru)

ACTION=$(echo "$SRC" | grep -oP '(?<=form method="post" id="loginForm" action=")[^"]+(?=")')
EXECUTION=$(echo "$SRC" | grep -oP '(?<=input type="hidden" name="execution" value=")[^"]+(?=")')

curl -s -L \
    -o /dev/null \
    -b /tmp/cookies.txt \
    -c /tmp/cookies.txt \
    --data-urlencode "inviteCode=" \
    --data-urlencode "execution=$EXECUTION" \
    --data-urlencode "_eventId=submit" \
    --data-urlencode "username=$USERNAME" \
    --data-urlencode "password=$PASSWORD" \
    https://login.1c.ru"$ACTION"


if ! grep -q "TGC" /tmp/cookies.txt ;then
    echo "Ошибка аутентификации"
    exit 1
fi
#


wgetlist=/tmp/1csrav-wget

#

#Функция для сравнения версий
#function version_platform { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }


while read -r fn; do

VERPLATFORM=$fn

#Заменяем точки на нижнее подчеркивание в версии платформы
VERPLATFORM1=${VERPLATFORM//./_}
#

#Точки в версии платформы
VERPLATFORM2=${VERPLATFORM//./}

    #Сравнение версий, если версия ниже 8.3.14.1944 то качаем после else
    if [ $(version_platform $VERPLATFORM) -ge $(version_platform "8.3.14.1944") ]; then

		    CLIENTLINK=$(curl -s -G \
		    -b /tmp/cookies.txt \
		    --data-urlencode "nick=Platform83" \
		    --data-urlencode "ver=$VERPLATFORM" \
		    --data-urlencode "path=Platform\\$VERPLATFORM1\\client_$VERPLATFORM1.deb64.tar.gz" \
		    https://releases.1c.ru/version_file | grep -m 1 -oP '(?<=a href=")[^"]+(?=">Скачать дистрибутив)')

		    SERVERLINK=$(curl -s -G \
		    -b /tmp/cookies.txt \
		    --data-urlencode "nick=Platform83" \
		    --data-urlencode "ver=$VERPLATFORM" \
		    --data-urlencode "path=Platform\\$VERPLATFORM1\\deb64_${VERPLATFORM1}.tar.gz" \
		    https://releases.1c.ru/version_file | grep -m 1 -oP '(?<=a href=")[^"]+(?=">Скачать дистрибутив)')

    else
		    CLIENTLINK=$(curl -s -G \
		    -b /tmp/cookies.txt \
		    --data-urlencode "nick=Platform83" \
		    --data-urlencode "ver=$VERPLATFORM" \
		    --data-urlencode "path=Platform\\$VERPLATFORM1\\client_$VERPLATFORM1.deb64.tar.gz" \
		    https://releases.1c.ru/version_file | grep -m 1 -oP '(?<=a href=")[^"]+(?=">Скачать дистрибутив)')

		    SERVERLINK=$(curl -s -G \
		    -b /tmp/cookies.txt \
		    --data-urlencode "nick=Platform83" \
		    --data-urlencode "ver=$VERPLATFORM" \
		    --data-urlencode "path=Platform\\$VERPLATFORM1\\deb64_${VERPLATFORM1}.tar.gz" \
		    https://releases.1c.ru/version_file | grep -m 1 -oP '(?<=a href=")[^"]+(?=">Скачать дистрибутив)')

    fi

        echo
        echo -e "\e[1;33;4;44mЗакачиваем клиентскую часть версии для архитектуры $VERPLATFORM "
        echo
        curl -# --fail -b /tmp/cookies.txt -o $UPLOADDIRPLATFORM/${VERPLATFORM}.client64.tar.gz -L "$CLIENTLINK"
        echo
        echo -e "\e[1;33;4;44mЗакачиваем серверную часть версии для архитектуры $VERPLATFORM"
        echo
        curl -# --fail -b /tmp/cookies.txt -o $UPLOADDIRPLATFORM/${VERPLATFORM}.server64.tar.gz -L "$SERVERLINK"
        echo -e "\e[0m"



echo "Распаковываем платформу 1C"

    tar -xvf $UPLOADDIRPLATFORM/${VERPLATFORM}.client64.tar.gz -C $UPLOADDIRPLATFORM
    tar -xvf $UPLOADDIRPLATFORM/${VERPLATFORM}.server64.tar.gz -C $UPLOADDIRPLATFORM

echo "Преобразовываем deb пакеты в tar.gz"
deb2targz $UPLOADDIRPLATFORM/*.deb

echo "Удаляем deb пакеты"
rm $UPLOADDIRPLATFORM/*.deb

echo "Перемещаем tar.gz в папку /var/calculate/distfiles"
mv $UPLOADDIRPLATFORM/*.tar.gz /var/calculate/distfiles

#удаляем папку
#rm -R $UPLOADDIRPLATFORM

echo "Теперь выполните комманду по установке 1С клиента, например emerge 1c-enterprise83-client-$VER"

done < $wgetlist
