#!/bin/bash

#Скрипт сравнения версий конфигурации 1С УТ 11 на сайте и в git репозитории

#read -p "Пользователь:" USERNAME
#read -p "Пароль:" PASSWORD
#read -p "Конфигурация:" CONFVERSION
CONFVERSION=Trade110
USERNAME=$1
PASSWORD=$2

#Подключаемся к серверу 1С
SRC=$(curl -c /tmp/cookies.txt -s -L https://releases.1c.ru)

ACTION=$(echo "$SRC" | grep -oP '(?<=form method="post" id="loginForm" action=")[^"]+(?=")')
EXECUTION=$(echo "$SRC" | grep -oP '(?<=input type="hidden" name="execution" value=")[^"]+(?=")')

curl -s -L \
    -o /dev/null \
    -b /tmp/cookies.txt \
    -c /tmp/cookies.txt \
    --data-urlencode "inviteCode=" \
    --data-urlencode "execution=$EXECUTION" \
    --data-urlencode "_eventId=submit" \
    --data-urlencode "username=$USERNAME" \
    --data-urlencode "password=$PASSWORD" \
    https://login.1c.ru"$ACTION"


if ! grep -q "TGC" /tmp/cookies.txt ;then
    echo "Ошибка аутентификации"
    exit 1
fi

#clear
echo
echo -e "\e[31;42mСписок версий для загрузки\e[0m"
echo

curl -s -b /tmp/cookies.txt https://releases.1c.ru/project/$CONFVERSION |

    grep 'a href="/version_files?nick='$CONFVERSION'' |
    tr -s '="  ' ' ' |
    tr -s '." ' ' ' |
#    awk -F ' ' '{print $7$8}' |
    awk -F ' ' '{print $5$6$7$8}' > /tmp/ut11srav
#    sort -Vr | pr -T -6

echo "В папке"

#Выводим список версий платформы
ls ../linuxbuh/app-office/1c-enterprise83-client/*.ebuild |
    grep 'ebuild' |
    tr -d '[:alpha:]' |
    tr -s '.." ' ' ' |
    tr -s '/" ' ' ' |
    tr -d '[=-=]' |
    awk -F ' ' '{print $4$5}' > /tmp/1csrav1

arr1=`cat /tmp/1csrav`
arr2=`cat /tmp/1csrav1`

if [ "${arr1[*]}" == "${arr2[*]}" ]; then echo "Файлы одинаковые"; else echo "Файлы разные"; fi

echo "head -n 10"
