#!/bin/bash

#Скрипт сравнения версий платформы 1С на сайте и в git репозитории

#read -p "Пользователь:" USERNAME
#read -p "Пароль:" PASSWORD
USERNAME=9257976
PASSWORD=ztd57s4s

#Функция для сравнения версий
#function version_platform { echo "$@" | awk -F. '{ printf("%d%03d%03d%03d\n", $1,$2,$3,$4); }'; }

#Сравнение версий, если версия ниже 8.3.12.1469 то качаем после else
#if [ $(version_platform $VERPLATFORM) -ge $(version_platform "8.3.14.1469") ]; then


#Подключаемся к серверу 1С
SRC=$(curl -c /tmp/cookies.txt -s -L https://releases.1c.ru)

ACTION=$(echo "$SRC" | grep -oP '(?<=form method="post" id="loginForm" action=")[^"]+(?=")')
EXECUTION=$(echo "$SRC" | grep -oP '(?<=input type="hidden" name="execution" value=")[^"]+(?=")')

curl -s -L \
    -o /dev/null \
    -b /tmp/cookies.txt \
    -c /tmp/cookies.txt \
    --data-urlencode "inviteCode=" \
    --data-urlencode "execution=$EXECUTION" \
    --data-urlencode "_eventId=submit" \
    --data-urlencode "username=$USERNAME" \
    --data-urlencode "password=$PASSWORD" \
    https://login.1c.ru"$ACTION"


if ! grep -q "TGC" /tmp/cookies.txt ;then
    echo "Ошибка аутентификации"
    exit 1
fi
#


echo "На сайте"

#Выводим список версий платформы на сайте
curl -s -b /tmp/cookies.txt https://releases.1c.ru/project/Platform83 |

    grep 'a href="/version_files?nick=Platform83' |
    tr -s '="  ' ' ' |
#    tr -s '."  ' ' ' |
    awk -F ' ' '{print $5}' |
    sed '/^8.3.3/d' |
    sed '/^8.3.4/d' |
    sed '/^8.3.5/d' |
    sed '/^8.3.6/d' |
    sed '/^8.3.7/d' |
    sed '/^8.3.8/d' |
    sed '/^8.3.9/d' |
    sed '/^8.3.10/d' |
    sed '/^8.3.11/d' |
    sed '/^8.3.12/d' |
    sed '/^8.3.13/d' > /tmp/1csrav


echo "В папке"

#Выводим список файлов в git папке
ls ../linuxbuh/app-office/1c-enterprise83-client/*.ebuild |
    grep 'ebuild' |
    sed -e 's|../linuxbuh/app-office/1c-enterprise83-client/1c-enterprise83-client-||' |
    sed -e 's|.ebuild||' > /tmp/1csrav1

#Сравниваем файлы для выявления разницы
arr1=`cat /tmp/1csrav`
arr2=`cat /tmp/1csrav1`

if [ "${arr1[*]}" == "${arr2[*]}" ]; then echo "Файлы одинаковые"; else echo "Файлы разные"; fi

echo "Нет таких файлов ebuild версий платформы"

comm -3 <(sort /tmp/1csrav) <(sort /tmp/1csrav1) > /tmp/1csrav-wget
